server:
  log_level: debug

traces:
  configs:
    - name: default
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
      remote_write:
        - endpoint: tempo:4317
          insecure: true
      batch:
        timeout: 5s
        send_batch_size: 100
