version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: product
    restart: on-failure

  product-service:
    image: product-service
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - 1000:8080
    restart: on-failure
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: product
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: test

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure
