version: "3.9"

services:
  postgres:
    container_name: product-service-postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: product
    restart: on-failure

  redis:
    image: redis
    container_name: basket-service-redis
    ports:
      - 6379:6379
    restart: on-failure
