services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: on-failure

  # Observability
  grafana:
    image: grafana/grafana-enterprise:10.4.2
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - 3000:3000
    restart: on-failure

  alloy:
    image: grafana/alloy:v1.0.0
    restart: on-failure
    volumes:
      - ./config/alloy:/etc/alloy
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LOKI_HOST: loki:3100
      TEMPO_HOST: tempo:4317
    depends_on:
      - loki
      - tempo
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental # Enable all functionality
    ports:
      - "12345:12345"
      # - "4317:4317"
      # - "4318:4318"

  loki:
    image: grafana/loki:2.9.7
    volumes:
      - ./config/loki/config.yml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml

  tempo:
    image: grafana/tempo:2.4.1
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ./config/tempo/tempo.yml:/etc/tempo.yml

  product-service:
    labels:
      grafana.logs/enabled: "true"
    image: product-service
    build:
      context: ./src/product-service
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    restart: on-failure
    environment:
      POSTGRES_HOST: host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: product
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: test
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
    depends_on:
      postgres:
        condition: service_healthy
