apiVersion: 1

datasources:
  # Loki for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    jsonData:
      timeout: 60
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"trace\.id":"([^"]+)"'
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"

  # Mimir for metrics
  - name: Metrics
    type: prometheus
    uid: metrics
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      prometheusType: Mimir
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: tempo

  # Tempo for logs
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
