// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type Response interface {
	IsResponse()
}

type Error struct {
	Message string `json:"message"`
	Path    string `json:"path"`
}

type ErrorPayload struct {
	Errors []*Error `json:"errors,omitempty"`
}

func (ErrorPayload) IsResponse() {}

type Mutation struct {
}

type Query struct {
}

type SigninPayload struct {
	Response Response `json:"response,omitempty"`
}

type SigninRequest struct {
	Email string `json:"email"`
}

type SignupPayload struct {
	Response Response `json:"response,omitempty"`
}

type SignupRequest struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Email     string `json:"email"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	Email     string    `json:"email"`
}

func (User) IsResponse() {}
