{
 "title": "RabbitMQ",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(rabbitmq_connections)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    { "expr": "sum(rabbitmq_channels)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "sum(rabbitmq_queues)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(rabbitmq_process_resident_memory_bytes / 1000000)",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=\"go-sse-rabbitmq-rabbitmq-1\"}[5m])) / sum(1024/container_spec_cpu_period{name=\"go-sse-rabbitmq-rabbitmq-1\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}